### ISSUE TITLE
Set up a cron job that runs the validation and publication process

### ISSUE THREAD

**Issue by clange** [mobivoc/vocol#27]
A task for either @lavdim or @np00 – please discuss who has most capacity to do it

Inside the VM please run the process

    if (vocabulary sources are valid)
    then publish them as HTML and LOD
    else report errors as issues

every 5 minutes or so, using a cron job.

See https://help.ubuntu.com/community/CronHowto (don't install *gnome-schedule*, which is just a GUI frontend, but … – maybe anacron?)

**Comment by lavdim** [comment]
Finished
