### ISSUE TITLE
Install cron if needed

### ISSUE THREAD

**Issue by clange** [mobivoc/vocol#44]
Apparently the Ubuntu base "box" for Vagrant already had cron installed. On our demo server this was not the case. bootstrap.sh should therefore at least *check* whether cron is available and, if not, install it.

**Comment by clange** [comment]
No, actually cron *was* installed on the demo server as well, but still it won't hurt to make sure. Let's treat this with a low priority ;-)

**Comment by lavdim** [comment]
Added a line to install Cron in boostrap
