### ISSUE TITLE
make sure that cronjob is run in the right directory

### ISSUE THREAD

**Issue by clange** [mobivoc/vocol#48]
@np00's new vocolJob.sh invokes some other programs using relative paths. For them to be found, the cronjob must be executed in the right directory. Crontab should look something like this:

    SHELL=/bin/bash
    PATH=/usr/local/bin:/usr/bin:/bin
    */5 * * * *     cd $HOME/place/of/the/github/repository/named/vocol; ./vocolJob.sh

(BTW this is a more elegant way to refer to the shell.)

It may be easier to prepare crontab as a *file*, instead of generating it on the fly with "echo".

**Comment by lavdim** [comment]
Path Corrected
